### ISSUE TITLE
Invalid trait conflict errors.

### ISSUE THREAD

**Issue by bweston92** [pdepend/pdepend#190]
In relation to #154 

```
trait A {
  function speak();
  function setMessage();
}
```

```
trait B {
  function speak();
}
```

```
class MyClass {
  use A, B {
    B::speak insteadof A
  }
}
```

Causes a message:
 `Trait method speak has not been applied, because there are collisions with other trait methods on \global\MyClass.`

**Comment by javier-rotelli** [comment]
this happens on 2.0.6.

**Comment by apolev** [comment]
Well actually it has been resolved particularly. Example above does not produce error, but let's make it a little bit complex. Something like this: https://gist.github.com/apolev/f345ada8066a95a3319a
This example produces error in pdepend, but works correctly in php 5.5.
If I detect the bug correctly, it's happened because ASTTraitUseStatement::getAllMethods returns 2 speakA methods: one from D and one from C which is superclass of D. We can see it if put break point at AbstractASTType::getTraitMethods(line 335, actually). When we evaluate $use->getAllMethods() we will get 2 absolutely similar speakA methods. 
Meanwhile I could not find an accurate solution, it looks like I should modify methods loading and do not load trait methods from parent. Unfortunately I don't know pdepend structure good enough to do this. 
But I found 2 dirty hacks to solve this problem: 
  * just comment throw new ASTTraitMethodCollisionException($method, $this); in AbstractASTType :-)
  * use B::speakA instead of A.

P.S. @manuelpichler, thanks for this project I'm really impressed amount of work you've done so far. You are rock!

**Comment by Jarry-code** [comment]
@apolev where? 
just downloaded 2.0.6 and this is happening.
i don't have a clue about how pdepend works, but if i can help let me know.

**Comment by bouland** [comment]
I have wrote another exemple for this bug.
https://gist.github.com/bouland/fc2a4f878009101c21be.js

**Comment by bweston92** [comment]
Closable?

**Comment by blat** [comment]
Not closable, issue still here :(

My use case:
```
trait TraitA
{
    public function foo()
    {
    }
}

trait TraitB
{
    use TraitA;
}

trait TraitC
{
    use TraitB;
}

trait TraitD
{
    public function foo()
    {
    }
}

abstract class ClassA
{
}

abstract class ClassB extends ClassA
{
}

abstract class ClassC extends ClassB
{
}

abstract class ClassD extends ClassC
{
}

class ClassE extends ClassD
{
    use TraitC, TraitD {
        TraitD::foo insteadof TraitC;
    }
}
```
This code is valid (works with PHP 7.1.7), but PHP_Depend 2.5.0 returns an exception:

> Trait method foo has not been applied, because there are collisions with other trait methods on \global\ClassE.

**Comment by bweston92** [comment]
The milestone may need updating then.

**Comment by bweston92** [comment]
Closing for inactivity.

**Comment by Fischer-Bjoern** [comment]
This issue still persists for PDepend 2.5.2.

Please reopen this issue.

**Comment by bweston92** [comment]
After more then 3 years I think it deserves a new issue with a new conversation based on the state of current development.
